"""
Project Atlas: Enterprise Decision Intelligence Platform

Data Quality Configuration

Purpose:
Central configuration for profiling and validation framework.
"""


import os


# =====================================================
# PROJECT PATHS
# =====================================================


PROJECT_ROOT = os.path.abspath(
    os.path.join(
        os.path.dirname(__file__),
        "../../"
    )
)


DATA_GENERATION_PATH = os.path.join(
    PROJECT_ROOT,
    "02_Data_Generation"
)



# =====================================================
# DATASET REGISTRY
# =====================================================

"""
All datasets generated by 02_Data_Generation.

The profiling engine will automatically
process every dataset listed here.
"""


DATASETS = {


    # =============================
    # DIMENSIONS
    # =============================


    "accounts":

        os.path.join(
            DATA_GENERATION_PATH,
            "dimensions/accounts/output/raw_accounts.csv"
        ),


    "customers":

        os.path.join(
            DATA_GENERATION_PATH,
            "dimensions/customers/output/raw_customers.csv"
        ),


    "employees":

        os.path.join(
            DATA_GENERATION_PATH,
            "dimensions/employees/output/raw_employees.csv"
        ),


    "locations":

        os.path.join(
            DATA_GENERATION_PATH,
            "dimensions/locations/output/raw_locations.csv"
        ),


    "machines":

        os.path.join(
            DATA_GENERATION_PATH,
            "dimensions/machines/output/raw_machines.csv"
        ),


    "products":

        os.path.join(
            DATA_GENERATION_PATH,
            "dimensions/products/output/raw_products.csv"
        ),


    "suppliers":

        os.path.join(
            DATA_GENERATION_PATH,
            "dimensions/suppliers/output/raw_suppliers.csv"
        ),



    # =============================
    # FACTS
    # =============================


    "sales":

        os.path.join(
            DATA_GENERATION_PATH,
            "facts/sales/output/raw_sales_transactions.csv"
        ),


    "inventory":

        os.path.join(
            DATA_GENERATION_PATH,
            "facts/inventory/output/raw_inventory.csv"
        ),


    "production":

        os.path.join(
            DATA_GENERATION_PATH,
            "facts/production/output/raw_production.csv"
        ),


    "maintenance":

        os.path.join(
            DATA_GENERATION_PATH,
            "facts/maintenance/output/raw_maintenance.csv"
        ),


    "finance":

        os.path.join(
            DATA_GENERATION_PATH,
            "facts/finance/output/raw_financial_transactions.csv"
        ),


    "budget":

        os.path.join(
            DATA_GENERATION_PATH,
            "facts/budgets/output/raw_budget.csv"
        ),


    "energy":

        os.path.join(
            DATA_GENERATION_PATH,
            "facts/energy/output/raw_energy_consumption.csv"
        ),


    "emissions":

        os.path.join(
            DATA_GENERATION_PATH,
            "facts/emissions/output/raw_emissions.csv"
        ),


    "waste":

        os.path.join(
            DATA_GENERATION_PATH,
            "facts/waste/output/raw_waste.csv"
        )

}



# =====================================================
# QUALITY THRESHOLDS
# =====================================================


MAX_MISSING_PERCENT = 5


MAX_DUPLICATE_PERCENT = 2


MIN_QUALITY_SCORE = 95



# =====================================================
# OUTPUT PATHS
# =====================================================


QUALITY_OUTPUT_PATH = os.path.join(

    os.path.dirname(__file__),

    "../profiling/output"

)


PROFILE_OUTPUT_PATH = os.path.join(

    QUALITY_OUTPUT_PATH,

    "profiles"

)